name: CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: execute unit tests
        run: yarn test

      - name: generate codecov report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

      - name: build dist
        run: yarn build
